#!/bin/sh

cd ~/.local/share/task/
message=$1 # First parameter will be the commit message

if [ ! -z "$1" ] # checking if the commit message is present. If not then simply commit with date.
then
  git-lazypush "$message"
else
  git-lazypush "$(date)"
fi

task sync
