(define-module (home yggdrasil packages)
  #:use-module (gnu packages))

(define-public packages
  (map (compose list specification->package+output)
       '("ungoogled-chromium-wayland"
         "ublock-origin-chromium"
         "pavucontrol"
         "bluez"
         "xdg-utils"
         "font-iosevka"
         "font-openmoji"
         "font-google-roboto"
         "font-google-noto"
         "bemenu"
         "swappy"
         "grim"
         "slurp"
         "wl-clipboard"
         "hicolor-icon-theme"
         "adwaita-icon-theme"
         "git:send-email"
         "xdg-desktop-portal"
         "xdg-desktop-portal-wlr"
         "direnv"
         "swayidle"
         "nyxt"
         "cl-slynk"
         "gstreamer"
         "gst-libav"
         "gst-plugins-base"
         "gst-plugins-good"
         "gst-plugins-bad"
         "gst-plugins-ugly"
         "acpi"
         "alsa-utils"
         "light"
         "wlsunset"
         "libnotify"
         "ripgrep"
         "pam-gnupg"
         "pinentry-bemenu"
         "rbw"
         "pinentry-qt"
         "pam-gnupg"
         "imv"
         "bc"
	 "fzf"
         "rsync"
         "zathura"
         "zathura-pdf-mupdf"
         "ffmpeg"
         "imv"
         "bc"
         "swayhide")))
