(define-module (home yggdrasil packages)
  #:use-module (gnu packages))

(define-public packages
  (map (compose list specification->package+output)
       '("ungoogled-chromium-wayland"
         #;"firefox-wayland"
         "telegram-desktop"
         "pavucontrol"
         "bluez"
         "alacritty"
         "xdg-utils"
         "font-iosevka"
         "font-openmoji"
         "font-google-roboto"
         "font-google-noto"
         "bemenu"
         "mako"
         "i3status"
         "swappy"
         "grim"
         "slurp"
         "wl-clipboard"
         "hicolor-icon-theme"
         "adwaita-icon-theme"
         "gnome-themes-standard"
         "git:send-email"
         "xdg-desktop-portal"
         "xdg-desktop-portal-wlr"
         "direnv"
         "swayidle"
         "nyxt"
         "cl-slynk"
         "gstreamer"
         "gst-libav"
         "gst-plugins-base"
         "gst-plugins-good"
         "gst-plugins-bad"
         "gst-plugins-ugly"
         )))
