(define-module (home yggdrasil terminals)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (gnu home services)
  #:use-module (gnu home-services terminals))

(define-public services
  (list
   (service
    home-alacritty-service-type
    (home-alacritty-configuration
     (config
      `((window . ((dynamic_title . true)))
        (background_opacity . 0.85)
        (cursor . ((style . ((shape . Block)))))
        (font . ((normal . ((family . "Iosevka Term")
                            (style . Oblique)))
                 (bold . ((family . "Iosevka Term")
                          (style . Semibold)))
                 (italic . ((family . "Iosevka Term")
                            (style . Italic)))
                 (size . 14.0)))
        (draw_bold_text_with_bright_colors . true)
        (colors . ((primary . ((background . "#2E3440")
                               (foreground . "#D8DEE9")
                               (dim_foreground . "#A5ABB6")))
                   (cursor . ((cursor . "#000000")
                              (text . "#2E3440")))
                   (vi_mode_cursor . ((text . "#2E3440")
                                      (cursor . "#D8DEE9")))
                   (selection . ((background . "#4C566A")
                                 (text . CellForeground)))
                   (normal . ((black . "#3B4252")
                              (red . "#BF616A")
                              (green . "#A3BE8C")
                              (yellow . "#EBCB8B")
                              (blue . "#81A1C1")
                              (magenta . "#B48EAD")
                              (cyan . "#88C0D0")
                              (white . "#E5E9F0")))
                   (bright . ((black . "#4C566A")
                              (red . "#BF616A")
                              (green . "#A3BE8C")
                              (yellow . "#EBCB8B")
                              (blue . "#81A1C1")
                              (magenta . "#B48EAD")
                              (cyan . "#8FBCBB")
                              (white . "#ECEFF4")))))
                   (dim . ((black . "#373E4D")
                           (red . "#94545D")
                           (green . "#809575")
                           (yellow . "#B29E75")
                           (blue . "#68809A")
                           (magenta . "#8C738C")
                           (cyan . "#6D96A5")
                           (white . "#AEB3BB")))
;;                   (search . (matches . (foreground . CellBackground)
;;                                      (background . "#88C0D0"))
;;                           (bar . (background "#434C5E")
;;                                (foreground "#D8DEE9")))))
        (key_bindings . #(((key . C)
                           (mods . Alt)
                           (action . Copy))
                          ((key . V)
                           (mods . Alt)
                           (action . Paste))))))))))
