
* Templates for guix projects

This directory provides templates for my guix-managed projects. This is a WIP. 

** Reproducibility

Packages are frozen with the use of the file =channels.scm=. Packages that are needed in a Guix profile are declared in =manifest.scm=. These two files combined with some command line commands are able to guarantee the code written will *always* be able to run in the same environment (provided one can install GNU guix on its machine). Guix is a relatively new tool already used by several scientists. See  https://10years.guix.gnu.org/video/guix-as-a-tool-for-computational-science/ to see how to use it for computational science.

The basic four commands highlighted in this video are the following :

- =guix shell= run in a controlled environment
- =guix describe= record software services
- =guix time-machine= replay software versions
- =guix pull= updates Guix with all its packages

** Improvements

Slight performance improvements can be attained using a Makefile (provided in this repo) an a local profile.  The basic idea is that =guix time-machine= is slow and can be avoided by using a local profile generated by =make profile=. Similarly, the basic commands are the following :

- =make shell= run in a controlled environment

Other possible improvements include using RDE in per-project features as highlighted by Andrew Tropin here : https://www.youtube.com/watch?v=H4hyNgXswik
