
* Dotfiles
** Why ?

I discovered system crafting / configuration thanks to LARBS / ArchLinux and
fell into the rabbithole of system configuration, mainly for long-term
efficiency reasons. I was happy with Arch, but then had some issues with my
computer, and found that portability and reproducibility is quite hard on Arch.

I discovered GNU Guix thanks to David Wilson and started to configure my system,
based on [[https://github.com/daviwil/dotfiles][David Wilson's]] and [[https://git.sr.ht/~krevedkokun/dotfiles][krevedkokun's dotfiles.]]

** Principles

- *Centrality*
Continuously working with the same language to keep improving experience with the system.

- *Naturalness*
Remove the border between mind and matter:
everything important should be as few keypresses as possible away from you,
and you shouldn't have to think about what you're doing.

- *Immersion / A coherent experience*
Everything will should revolve around a very similar experience : languages,
keyboard shortcuts, help... Most programs use vim keys when possible.

- *Cutting-edge / Rolling*
The rolling release system of guix should allow having a cutting-edge distribution
in only a few years.

- *Safety*
Do not compromise safety with the possibility to safely roll-back.

- *Reproductibility*
Moving from a device to another one without having to configure things too much
Everything should be very simple to reproduce.

- *Economy / Minimalism*
Programs should be simple and light on system resources and highly extensible.

** What is not reproducible ?

- some RSA keys

- all passwords and logins rely on my bitwarden database through rbw
