#!/bin/sh

# The clickable help menu. Middle click to restart wm.

# If dwm is running, use dwm's readme and restart.
pidof dwm >/dev/null &&
#	READMEFILE="${XDG_DATA_HOME:-$HOME/.local/share}/help/my_larbs.rmd" #/usr/local/share/dwm/larbs.mom
	READMEFILEBASE="${XDG_DATA_HOME:-$HOME/.local/share}/help/my_larbs" #/usr/local/share/dwm/larbs.mom
	restartwm() { pkill -HUP dwm ;} ||
		restartwm() { i3 restart ;}

case $BLOCK_BUTTON in
	1) zathura "${READMEFILEBASE}.pdf" ;;
	2) Rscript -e "rmarkdown::render('${READMEFILEBASE}.rmd', quiet=TRUE)" ;;
	3) notify-send "❓ Help module" "\- Left click to open my_larbs guide.
- Middle click to refresh my_larbs help file." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac; echo "❓"
