#!/usr/bin/env sh

# sudo not required for some system commands
for command in mount umount sv updatedb su ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
        gams="flatpak run --filesystem=/home/graves/.var/app/org.flatpak.GAMS/data/gamslice.txt --filesystem=/home/graves/docs/eeet/ org.flatpak.GAMS" \
        zoom="swayhide flatpak run us.zoom.Zoom" \
        skype="swayhide flatpak run com.skype.Client" \
        ferdi="swayhide flatpak run com.getferdi.Ferdi"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR -t" \

alias \
	mr="sudo modprobe -r psmouse && sudo modprobe psmouse" \
        kanshi='wlr-randr --output eDP-1 --off'
