
window: 
  dynamic_title: true
background_opacity: 0.85
cursor: 
  style: 
    shape: Block
font: 
  normal: 
    family: 'Iosevka Term'
    style: Oblique
  bold: 
    family: 'Iosevka Term'
    style: Semibold
  italic: 
    family: 'Iosevka Term'
    style: Italic
  size: 14.0
draw_bold_text_with_bright_colors: true
colors: 
  primary: 
    background: '#2E3440'
    foreground: '#D8DEE9'
    dim_foreground: '#A5ABB6'
  cursor: 
    cursor: '#000000'
    text: '#2E3440'
  vi_mode_cursor: 
    text: '#2E3440'
    cursor: '#D8DEE9'
  selection: 
    background: '#4C566A'
    text: CellForeground
  normal: 
    black: '#3B4252'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#88C0D0'
    white: '#E5E9F0'
  bright: 
    black: '#4C566A'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#8FBCBB'
    white: '#ECEFF4'
dim: 
  black: '#373E4D'
  red: '#94545D'
  green: '#809575'
  yellow: '#B29E75'
  blue: '#68809A'
  magenta: '#8C738C'
  cyan: '#6D96A5'
  white: '#AEB3BB'
key_bindings: 
  - 
    key: C
    mods: Alt
    action: Copy
  - 
    key: V
    mods: Alt
    action: Paste
  - 
    key: P
    mods: Control
    action: Paste
  - 
    key: Insert
    mods: Shift
    action: Paste
  - 
    key: Y
    mods: Control
    action: Copy
  - 
    key: Key0
    mods: Control
    action: ResetFontSize
  - 
    key: Equals
    mods: Control
    action: IncreaseFontSize
  - 
    key: Plus
    mods: Control
    action: IncreaseFontSize
  - 
    key: Minus
    mods: Control
    action: DecreaseFontSize
  - 
    key: Space
    mods: Control
    mode: Vi
    action: ScrollToBottom
  - 
    key: Space
    mods: Control
    action: ToggleViMode
  - 
    key: I
    mode: Vi
    action: ScrollToBottom
  - 
    key: I
    mode: Vi
    action: ToggleViMode
  - 
    key: C
    mods: Control
    mode: Vi
    action: ScrollToBottom
  - 
    key: C
    mods: Control
    mode: Vi
    action: ToggleViMode
  - 
    key: Escape
    mode: Vi
    action: ClearSelection
  - 
    key: Y
    mods: Control
    mode: Vi
    action: ScrollLineUp
  - 
    key: E
    mods: Control
    mode: Vi
    action: ScrollLineDown
  - 
    key: G
    mode: Vi
    action: ScrollToTop
  - 
    key: G
    mods: Shift
    mode: Vi
    action: ScrollToBottom
  - 
    key: B
    mods: Control
    mode: Vi
    action: ScrollPageUp
  - 
    key: F
    mods: Control
    mode: Vi
    action: ScrollPageDown
  - 
    key: U
    mods: Control
    mode: Vi
    action: ScrollHalfPageUp
  - 
    key: D
    mods: Control
    mode: Vi
    action: ScrollHalfPageDown
  - 
    key: Y
    mode: Vi
    action: Copy
  - 
    key: Y
    mods: Control
    mode: Vi
    action: ClearSelection
  - 
    key: V
    mode: Vi
    action: ToggleNormalSelection
  - 
    key: V
    mods: Shift
    mode: Vi
    action: ToggleLineSelection
  - 
    key: V
    mods: Control
    mode: Vi
    action: ToggleBlockSelection
  - 
    key: V
    mods: Alt
    mode: Vi
    action: ToggleSemanticSelection
  - 
    key: Return
    mode: Vi
    action: Open
  - 
    key: K
    mode: Vi
    action: Up
  - 
    key: J
    mode: Vi
    action: Down
  - 
    key: H
    mode: Vi
    action: Left
  - 
    key: L
    mode: Vi
    action: Right
  - 
    key: Up
    mode: Vi
    action: Up
  - 
    key: Down
    mode: Vi
    action: Down
  - 
    key: Left
    mode: Vi
    action: Left
  - 
    key: Right
    mode: Vi
    action: Right
  - 
    key: Key0
    mode: Vi
    action: First
  - 
    key: Key4
    mode: Vi
    action: Last
  - 
    key: Key6
    mods: Shift
    mode: Vi
    action: FirstOccupied
  - 
    key: H
    mods: Shift
    mode: Vi
    action: High
  - 
    key: M
    mods: Shift
    mode: Vi
    action: Middle
  - 
    key: L
    mods: Shift
    mode: Vi
    action: Low
  - 
    key: B
    mode: Vi
    action: SemanticLeft
  - 
    key: W
    mode: Vi
    action: SemanticRight
  - 
    key: E
    mode: Vi
    action: SemanticRightEnd
  - 
    key: B
    mods: Shift
    mode: Vi
    action: WordLeft
  - 
    key: W
    mods: Shift
    mode: Vi
    action: WordRight
  - 
    key: E
    mods: Shift
    mode: Vi
    action: WordRightEnd
  - 
    key: Key5
    mods: Shift
    mode: Vi
    action: Bracket
  - 
    key: Slash
    mode: Vi
    action: SearchForward
  - 
    key: Slash
    mods: Shift
    mode: Vi
    action: SearchBackward
  - 
    key: N
    mode: Vi
    action: SearchNext
  - 
    key: N
    mods: Shift
    mode: Vi
    action: SearchPrevious