(define-module (server mail)
  #:use-module (server maildir-utils)
  #:use-module (ice-9 match)
  #:use-module (ice-9 format)
  #:use-module (srfi srfi-1)
  #:use-module (gnu home services)
  #:use-module (gnu home-services-utils)
  #:use-module (gnu home-services mail)
  ;; #:use-module (gnu home-services state)
  ;; #:use-module (gnu home-services password-utils)
  ;; #:use-module (gnu home-services version-control)
  #:use-module (gnu services)
  #:use-module (gnu services shepherd)
  #:use-module (gnu services configuration)
  #:use-module (gnu packages ssh)
  #:use-module (gnu packages mail)
  #:use-module (guix packages)
  #:use-module (guix gexp)
  #:use-module (guix build utils))

(define-public packages
  '("isync"))

(define-public services

  (let ((data_home "/var")
        (user_nngraves (getenv "USER_NNGRAVES"))
        (user_neleves (getenv "USER_NELEVES"))
        (user_ngmx (getenv "USER_NGMX"))
        (user_ngmail (getenv "USER_NGMAIL"))
        (user_cpure (getenv "USER_CPURE"))
        (user_qpure (getenv "USER_QPURE"))
        (user_pgmail (getenv "USER_PGMAIL")))
    (list
   ;; (simple-service
   ;;  'add-password-store-git-state
   ;;  state-service-type
   ;;  (list
   ;;   (state-git
   ;;    (string-append (getenv "XDG_STATE_HOME") "/password-store")
   ;;    "/srv/git/pass.git")))
   ;; (service
   ;;  home-password-store-service-type
   ;;  (home-password-store-configuration))
     (service
      isync-service-type
      (isync-configuration
       (config
        `((IMAPStore ,(string-append user_nngraves "-remote"))
          (Host SSL0.OVH.NET)
          (Port 993)
          (User ,user_nngraves)
          (Pass ,(getenv "PASS_NNGRAVES"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_nngraves "-local"))
          (Subfolders Legacy)
          (Path ,(string-append data_home "/mail/" user_nngraves "/"))
          (Inbox ,(string-append data_home "/mail/" user_nngraves "/INBOX"))
          ,#~""
          (Channel ,user_nngraves)
          (Expunge Both)
          (Far ,(string-append ":" user_nngraves "-remote:"))
          (Near ,(string-append ":" user_nngraves "-local:"))
          (Patterns * !"Local_Archives")
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          ,#~""
          (IMAPStore ,(string-append user_neleves "-remote"))
          (Host messagerie.enpc.fr)
          (Port 993)
          (User ,user_neleves)
          (Pass ,(getenv "PASS_NELEVES"))
          (CipherString DEFAULT@SECLEVEL=1)
          (PipelineDepth 1)
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_neleves "-local"))
          (Subfolders Verbatim)
          (Path ,(string-append data_home "/mail/" user_neleves "/"))
          (Inbox ,(string-append data_home "/mail/" user_neleves "/INBOX"))
          ,#~""
          (Channel ,user_neleves)
          (Expunge Both)
          (Far ,(string-append ":" user_neleves "-remote:"))
          (Near ,(string-append ":" user_neleves "-local:"))
          (Patterns * !"Local_Archives")
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          (IMAPStore ,(string-append user_ngmx "-remote"))
          (Host imap.gmx.net)
          (Port 993)
          (User ,user_ngmx)
          (Pass ,(getenv "PASS_NGMX"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_ngmx "-local"))
          (Subfolders Verbatim)
          (Path ,(string-append data_home "/mail/" user_ngmx "/"))
          (Inbox ,(string-append data_home "/mail/" user_ngmx "/INBOX"))
          ,#~""
          (Channel ,user_ngmx)
          (Expunge Both)
          (Far ,(string-append ":" user_ngmx "-remote:"))
          (Near ,(string-append ":" user_ngmx "-local:"))
          (Patterns * !"Local_Archives")
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          ,#~""
          (IMAPStore ,(string-append user_ngmail "-remote"))
          (Host imap.gmail.com)
          (Port 993)
          (User ,user_ngmail)
          (Pass ,(getenv "PASS_NGMAIL"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_ngmail "-local"))
          (Subfolders Verbatim)
          (Path ,(string-append data_home "/mail/" user_ngmail "/"))
          (Inbox ,(string-append data_home "/mail/" user_ngmail "/INBOX"))
          ,#~""
          (Channel ,user_ngmail)
          (Expunge Both)
          (Far ,(string-append ":" user_ngmail "-remote:"))
          (Near ,(string-append ":" user_ngmail "-local:"))
          (Patterns * !"[Gmail]/All Mail" !"[Gmail]/Important"
                    !"[Gmail]/Starred" !"[Gmail]/Bin" !"Local_archives")
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          (IMAPStore ,(string-append user_cpure "-remote"))
          (Host ssl0.ovh.net)
          (Port 993)
          (User ,user_cpure)
          (Pass ,(getenv "PASS_CPURE"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_cpure "-local"))
          (Subfolders Legacy)
          (Path ,(string-append data_home "/mail/" user_cpure "/"))
          (Inbox ,(string-append data_home "/mail/" user_cpure "/INBOX"))
          ,#~""
          (Channel ,user_cpure)
          (Expunge Both)
          (Far ,(string-append ":" user_cpure "-remote:"))
          (Near ,(string-append ":" user_cpure "-local:"))
          (Patterns *)
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          (IMAPStore ,(string-append user_qpure "-remote"))
          (Host pro1.mail.ovh.net)
          (Port 993)
          (User user_qpure)
          (Pass ,(getenv "PASS_QPURE"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_qpure "-local"))
          (Subfolders Verbatim)
          (Path ,(string-append data_home "/mail/" user_qpure "/"))
          (Inbox ,(string-append data_home "/mail/" user_qpure "/INBOX"))
          ,#~""
          (Channel ,user_qpure)
          (Expunge Both)
          (Far ,(string-append ":" user_qpure "-remote:"))
          (Near ,(string-append ":" user_qpure "-local:"))
          (Patterns *)
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)
          ,#~""
          ,#~""
          (IMAPStore ,(string-append user_pgmail "-remote"))
          (Host imap.gmail.com)
          (Port 993)
          (User ,user_pgmail)
          (Pass ,(getenv "PASS_PGMAIL"))
          (AuthMechs LOGIN)
          (SSLType IMAPS)
          (CertificateFile /etc/ssl/certs/ca-certificates.crt)
          ,#~""
          (MaildirStore ,(string-append user_pgmail "-local"))
          (Subfolders Verbatim)
          (Path ,(string-append data_home "/mail/" user_pgmail "/"))
          (Inbox ,(string-append data_home "/mail/" user_pgmail "/INBOX"))
          ,#~""
          (Channel ,user_pgmail)
          (Expunge Both)
          (Far ,(string-append ":" user_pgmail "-remote:"))
          (Near ,(string-append ":" user_pgmail "-local:"))
          (Patterns * !"[Gmail]/All Mail")
          (Create Both)
          (SyncState *)
          (MaxMessages 0)
          (ExpireUnread no)))))
     )))
