#!/run/current-system/profile/bin/guile -s
!#

(use-modules (guix profiles))

(define (find-home str)
    (if (string-prefix? "~" str)
        (string-append (@ (shepherd support) user-homedir)
                       (string-drop str 1))))

(let* ((commit-msg-file (cadr (command-line))))
  (with-output-to-file
      commit-msg-file
    (lambda _
      (display "\n\nThis commit has been produced in the following environment:\n")
      (map
       (lambda (x)
         (let* ((elts (cdadar (manifest-entry-properties x)))
                ;; probably no need for repository-open here.
                (repository (car (assoc-ref elts 'url)))
                (commit (car (assoc-ref elts 'commit))))
           (format #t "~a:~a\n" repository commit)))
       (manifest-entries
        (profile-manifest (find-home "~/.config/guix/current")))))))