#!/bin/bash

#task status:pending and due export |
#	sed "1d;\$d" |
#	awk -F '"' '{ print $10,"(due)",$6 }' |
#	sed "s/^20\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)T\([0-9][0-9]\)\([0-9][0-9]\)[^ ]* \(.*\)$/-\3\/\2\/\1 @ \4:\5 -> \3\/\2\/\1 @ \4:\5|\6/" > "${XDG_DATA_HOME}/calcurse/apts"

#task status:pending and due export |
#	jq '.[] | .due, " (due) " +.description+ "~"' -j |
#	sed "s/20\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)T\([0-9][0-9]\)\([0-9][0-9]\)[^ ]* /\2\/\3\/\1 @ \4:\5 -> \2\/\3\/\1 @ \4:\5|/g" |
#	tr '~' '\n' > "${XDG_DATA_HOME}/calcurse/apts"

#task status:pending and scheduled and until export |
#	jq '.[] |.scheduled, " "+.until, " (sch) " +.description+ "~"' -j |
#	sed "s/20\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)T\([0-9][0-9]\)\([0-9][0-9]\)[^ ]* /-\2\/\3\/20\1 @ \4:\5|/g" |
#	tr '~' '\n' |
#	sed -e 's/|-/ -> /' -e 's/^-//' > "${XDG_DATA_HOME}/calcurse/apts"

task status:pending and scheduled and until export |
	jq '.[] |.scheduled, "|"+.until, "|(sch) " +.description+ "~"' -j |
	tr '~' '\n' |
	~/.local/bin/rust/taskwarrior_to_calcurse/main --offset "$(timedatectl | sed -n '4{p;q}' | sed 's/^.*+\([0-9][0-9][0-9][0-9]\))$/\100/')" > "${XDG_DATA_HOME}/calcurse/apts"

task status:pending and scheduled:today export | jq '.[].description' > "${XDG_DATA_HOME}/calcurse/todo"
