#!/usr/bin/env sh

name=$(rbw list | $MENU -i -p "Which password ?")
if [ -z $name ]
then
	notify-send "menu_rbw no selection"
	exit 1
fi
full=$(rbw get "$name" --full | head -2)
#username
username=$(echo "$full" | tail -1 | cut -d' ' -f2-)
echo "$username" | wl-copy --primary --trim-newline
#password
echo "$full" | head -1 | wl-copy --trim-newline
notify-send "menupass $name copied" && sleep 15 && wl-copy --clear
