#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.dotfiles/home/yggdrasil/files/share/emoji | $MENU -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
        notify-send "The migration has not been done for this part of the script yet. ydotool."
	#xdotool type "$chosen"
else
	printf "$chosen" | wl-copy # By default copying to clipboard.
	notify-send "'$chosen' copied to clipboard." &
fi
