#!/bin/sh
# Originally, I was using the --paste-once approach, but it sometimes makes chrome and other apps crash.
shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

passname_full=$(printf '%s\n' "${password_files[@]}" |  $MENU -i -p "Which password ?" "$@")

if [ -z $passname_full ]
then
	notify-send "menupass no selection"
	exit 1
fi

#username
echo "$passname_full" | cut -d'/' -f1 | wl-copy --primary --trim-newline

#password
pass show "$passname_full" | wl-copy --trim-newline

notify-send "menupass $passname_full copied" && sleep 15 && wl-copy --clear
