#!/bin/sh

music="$(find $XDG_MUSIC_DIR -type f -print | sed -e 's/^.*music\///g' | $MENU -i -l 20 --scrollbar autohide -p 'Which song ?' )"

if [ -z "$music" ]
then
	notify-send "playm no selection"
	exit 1
fi

notify-send "playing $music" && mpv --no-video --no-audio-display --no-resume-playback "$XDG_MUSIC_DIR/$music"
