#!/usr/bin/env sh

# A dmenu-like wrapper script for system functions.

cmds="\
🚪 exit sway	swaymsg exit
🔒 lock	/run/setuid-programs/swaylock
♻ reload sway	swaymsg reload
😪 suspend	loginctl suspend
🐻 hibernate	loginctl suspend-then-hibernate
🔃 reboot	loginctl reboot
🖥 shutdown	loginctl poweroff"

choice="$(echo "$cmds" | cut -d'	' -f 1 | ${MENU})" || exit 1

eval "$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-)"
