#!/usr/bin/env sh

# Low-level simple and integrated bibliography workflow.

# An *entry* is a bibliographic record that contains citation information. It is
# identified by a citation key. For each entry we take a *note* using org-roam
# (it probably works with various note-taking software), and we can archive
# an associated *file* in the directory files/library. These files can be
# saved in a S3 bucket using `lfs-s3`.

# To use this hook, simply ln -s\
# ~/spheres/info/dots/files/git-biblio-prepare-commit-msg\
# ~/resources/.git/hooks/prepare-commit-msg

exec emacsclient --eval "(citadel-write-commit-message \"$1\")"
