#!/bin/sh

name=$(rbw list | $MENU -i)
if [ -z $name ]
then
	notify-send "menu_rbw no selection"
	exit 1
fi
full=$(rbw get "$name" --full | head -2)
#username
username=$(echo "$full" | tail -1 | cut -d' ' -f2-)
echo "$username" | wl-copy --primary --paste-once
#password
echo "$full" | head -1 | wl-copy --paste-once
notify-send "menu_rbw $name copied"
