#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds scripts to $PATH
export PATH="$PATH":"${XDG_CONFIG_HOME:-$HOME/.config}/guix/current/bin":"$HOME/spheres/info/dotfiles/home/scripts":"$(find ~/spheres/info/dotfiles/home/scripts -type d -printf %p:)""$HOME/.local/share/cargo/bin":"$HOME/.local/share/flatpak/exports/bin"

# Adds flatpak data dirs
export XDG_DATA_DIRS=$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:/home/graves/.local/share/flatpak/exports/share

# quickfix to enable XDG user directories
set -o allexport && source "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" && set +o allexport

# Load the default Guix profile
GUIX_PROFILE="$HOME/.guix-profile"
. "$GUIX_PROFILE"/etc/profile

# Default programs:
export EDITOR="swayhide emacsclient -c"
export TERMINAL="alacritty"
export BROWSER="chromium"
export MENU="bemenu"

# ~/ Clean-up:
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
#export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"

export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export RUSTUP_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"

# Other program settings:
export SUDO_ASKPASS="$HOME/spheres/info/dotfiles/home/scripts/menuaskpass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export ABDUCO_CMD=""
export WLR_DRM_NO_MODIFIERS=1 #fixed in mesa 21, see github sway wiki, for nouveau driver

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &
